# alertmanager.yml - AlertManager configuration for TimeCard monitoring

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'timecard-alerts@example.com'
  smtp_auth_username: 'alerts'
  smtp_auth_password: 'password'

# Шаблоны для уведомлений
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Маршрутизация алертов
route:
  group_by: ['alertname', 'device_id', 'severity']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  
  routes:
    # Критические алерты - немедленное уведомление
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 5m
      
    # PTP алерты
    - match:
        component: ptp
      receiver: 'ptp-team'
      group_wait: 30s
      repeat_interval: 30m
      
    # Тепловые алерты
    - match:
        component: thermal
      receiver: 'thermal-alerts'
      group_wait: 1m
      repeat_interval: 15m
      
    # GNSS алерты
    - match:
        component: gnss
      receiver: 'gnss-team'
      group_wait: 2m
      repeat_interval: 1h
      
    # Алерты питания
    - match:
        component: power
      receiver: 'power-team'
      group_wait: 1m
      repeat_interval: 30m
      
    # Системные алерты
    - match:
        component: system
      receiver: 'system-admin'
      group_wait: 30s
      repeat_interval: 1h

# Получатели уведомлений
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        
  - name: 'critical-alerts'
    email_configs:
      - to: 'critical-alerts@example.com'
        subject: '🚨 CRITICAL: TimeCard Alert on {{ .GroupLabels.device_id }}'
        body: |
          TimeCard Critical Alert
          
          Device: {{ .GroupLabels.device_id }}
          Severity: {{ .GroupLabels.severity }}
          
          Alerts:
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            {{ .Annotations.description }}
          {{ end }}
          
          Dashboard: http://localhost:3000/d/timecard
          
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#critical-alerts'
        color: 'danger'
        title: '🚨 Critical TimeCard Alert'
        text: |
          Device: {{ .GroupLabels.device_id }}
          {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
        
  - name: 'ptp-team'
    email_configs:
      - to: 'ptp-team@example.com'
        subject: '⏰ PTP Alert: {{ .GroupLabels.device_id }}'
        body: |
          PTP System Alert
          
          Device: {{ .GroupLabels.device_id }}
          Component: PTP
          
          Details:
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            {{ .Annotations.description }}
          {{ end }}
          
          Grafana: http://localhost:3000/d/timecard?var-device={{ .GroupLabels.device_id }}
          
  - name: 'thermal-alerts'
    email_configs:
      - to: 'thermal-team@example.com'
        subject: '🌡️ Thermal Alert: {{ .GroupLabels.device_id }}'
        body: |
          Thermal System Alert
          
          Device: {{ .GroupLabels.device_id }}
          Component: Thermal Management
          
          Details:
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            Temperature: {{ .Annotations.description }}
          {{ end }}
          
          Action Required: Check cooling system and ambient temperature
          Dashboard: http://localhost:3000/d/timecard?var-device={{ .GroupLabels.device_id }}
          
  - name: 'gnss-team'
    email_configs:
      - to: 'gnss-team@example.com'
        subject: '🛰️ GNSS Alert: {{ .GroupLabels.device_id }}'
        body: |
          GNSS System Alert
          
          Device: {{ .GroupLabels.device_id }}
          Component: GNSS Receiver
          
          Details:
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            {{ .Annotations.description }}
          {{ end }}
          
          Possible Causes:
          - Antenna position/connection
          - Signal interference
          - Satellite visibility
          
          Dashboard: http://localhost:3000/d/timecard?var-device={{ .GroupLabels.device_id }}
          
  - name: 'power-team'
    email_configs:
      - to: 'power-team@example.com'
        subject: '⚡ Power Alert: {{ .GroupLabels.device_id }}'
        body: |
          Power System Alert
          
          Device: {{ .GroupLabels.device_id }}
          Component: Power Management
          
          Details:
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            {{ .Annotations.description }}
          {{ end }}
          
          Check:
          - Power supply stability
          - Voltage rail health
          - Current consumption
          
          Dashboard: http://localhost:3000/d/timecard?var-device={{ .GroupLabels.device_id }}
          
  - name: 'system-admin'
    email_configs:
      - to: 'admin@example.com'
        subject: '🔧 System Alert: {{ .GroupLabels.device_id }}'
        body: |
          System Alert
          
          Device: {{ .GroupLabels.device_id }}
          Component: {{ .GroupLabels.component }}
          
          Details:
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
            {{ .Annotations.description }}
          {{ end }}
          
          Monitoring Dashboard: http://localhost:3000/d/timecard
          API Status: http://localhost:8080/api/health

# Подавление алертов
inhibit_rules:
  # Подавляем warning если есть critical
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['device_id', 'component']
    
  # Подавляем дублированные алерты
  - source_match:
      alertname: 'SystemHealthCritical'
    target_match_re:
      alertname: '.*(Warning|Low).*'
    equal: ['device_id']