# Quantum-PCI TimeCard Monitoring configuration

version: "1.0.1"

server:
  port: 8080
  async_mode: "threading"  # options: threading, eventlet, gevent
  cors_allowed_origins:
    - "http://localhost:8080"
    - "http://127.0.0.1:8080"
    - "http://localhost"

monitoring:
  update_interval_seconds: 5
  history_maxlen: 1000

alerts:
  ptp:
    offset_ns:
      warning: 1000
      critical: 10000
    drift_ppb:
      warning: 100
      critical: 1000
  gnss:
    sync_status:
      warning: "LOST"
      critical: "LOST"

static:
  allowed_extensions:
    - ".html"
    - ".css"
    - ".js"
    - ".svg"
    - ".png"
    - ".ico"
  allowed_dashboard_files:
    - "real-dashboard.html"
    - "simple-dashboard.html"

