# grafana-datasource.yml - Grafana datasource provisioning

apiVersion: 1

# Источники данных
datasources:
  # Prometheus - основной источник метрик
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    version: 1
    jsonData:
      timeInterval: "30s"
      queryTimeout: "60s"
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
    
  # VictoriaMetrics - long-term storage
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: false
    editable: true
    version: 1
    jsonData:
      timeInterval: "1m"
      queryTimeout: "300s"
      httpMethod: POST
      
  # TimeCard API - прямой доступ к API
  - name: TimeCard-API
    type: simplejson
    access: proxy
    url: http://timecard-api:8080
    isDefault: false
    editable: true
    version: 1
    jsonData:
      authentication: "none"